spring:
  application:
    name: tutor-spring
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: admin
    locations:
      filesystem:db.migration
    baselineOnMigrate: true